quarkus.azure-functions.app-name=az-func-feedback-report
quarkus.azure-functions.runtime.java-version=25

# ------------------------------------------------------------
# Report Storage
# ------------------------------------------------------------
app.reports.storage.connection-string=${kv//FeedbackReportStorageConnectionString:}
app.reports.storage.container-name=${kv//FeedbackReportContainerName:feedback-reports}

# Database
quarkus.datasource.db-kind=${FEEDBACK_DB_KIND:postgresql}
quarkus.datasource.jdbc.url=${FEEDBACK_DB_URL:${kv//FeedBackDBUrl:jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}}
quarkus.datasource.username=${FEEDBACK_DB_USER:${kv//FeedbackDBUser:sa}}
quarkus.datasource.password=${FEEDBACK_DB_PASSWORD:${kv//FeedBackDBPassword:sa}}

# key vault
quarkus.azure.keyvault.secret.endpoint=${QUARKUS_AZURE_KEYVAULT_SECRET_ENDPOINT:}
