quarkus.azure-functions.app-name=az-func-feedback-report
quarkus.azure-functions.runtime.java-version=25

# ------------------------------------------------------------
# Report Storage
# ------------------------------------------------------------
app.reports.storage.connection-string=${kv//FeedbackReportStorageConnectionString:}
app.reports.storage.container-name=${kv//FeedbackReportContainerName:feedback-reports}

%dev.app.reports.storage.connection-string=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;
%dev.app.reports.storage.container-name=feedback-reports

# Database
quarkus.datasource.db-kind=${FEEDBACK_DB_KIND:postgresql}
quarkus.datasource.jdbc.url=${FEEDBACK_DB_URL:${kv//FeedBackDBUrl:jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}}
quarkus.datasource.username=${FEEDBACK_DB_USER:${kv//FeedbackDBUser:sa}}
quarkus.datasource.password=${FEEDBACK_DB_PASSWORD:${kv//FeedBackDBPassword:sa}}

# key vault
quarkus.azure.keyvault.secret.endpoint=${QUARKUS_AZURE_KEYVAULT_SECRET_ENDPOINT:}


# ------------------------------------------------------------
# Perfil DEV - execução local com mvn quarkus:dev
# ------------------------------------------------------------
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:feedback_dev;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=sa

%dev.app.email.connection-string=endpoint=https://localhost;accesskey=mock
%dev.app.admin-emails=test@example.com
%dev.app.email.sender-address=test@example.com
%dev.app.email.subject=Feedback Dev

%dev.quarkus.otel.enabled=false
%dev.quarkus.otel.sdk.disabled=true